name: Deploy on heroku

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "websocket-typer"
          heroku_email: "gaurondorian@gmail.com"
          usedocker: true
          appdir: "backend"
